export const mockSeiProcesses = [
  {
    id: '1',
    sei_number: '1630.01.0001450/2025-42',
    link: 'https://sei.mg.gov.br/sei/controlador.php?acao=procedimento_trabalhar&id_procedimento=12345',
    ref_year: 2025,
    type: 'Prestação de Contas',
    description: 'Análise preliminar da prestação de contas anual referente ao exercício de 2024.',
    tags: ['Urgente', 'Financeiro'],
    status: 'Acompanhamento especial',
    assigned_to: 'Ana Silva',
    initials: 'AS',
    notes: 'Aguardando envio dos balancetes complementares.',
    received_date: '2025-01-15',
    deadline: '2025-02-15',
    response_date: null,
    has_dilation: false,
    dilation_process: null,
    dilation_deadline: null
  },
  {
    id: '2',
    sei_number: '1630.01.0002100/2025-11',
    link: '#',
    ref_year: 2025,
    type: 'Diligência',
    description: 'Solicitação de esclarecimentos sobre contrato de aluguel de impressoras.',
    tags: ['Contratos', 'Administrativo'],
    status: 'Aguarda resposta',
    assigned_to: 'Carlos Eduardo',
    initials: 'CE',
    notes: 'Ofício enviado em 10/01. Prazo correndo.',
    received_date: '2025-01-10',
    deadline: '2025-01-30',
    response_date: null,
    has_dilation: true,
    dilation_process: '1630.01.0002105/2025-99',
    dilation_deadline: '2025-02-28'
  },
  {
    id: '3',
    sei_number: '1630.01.0000500/2024-88',
    link: '#',
    ref_year: 2024,
    type: 'Auditoria',
    description: 'Relatório final de auditoria nas contas de gestão fiscal.',
    tags: ['Auditoria', 'Compliance'],
    status: 'Finalizado e Concluído',
    assigned_to: 'Roberto Campos',
    initials: 'RC',
    notes: 'Arquivado conforme despacho.',
    received_date: '2024-11-20',
    deadline: '2024-12-20',
    response_date: '2024-12-18',
    has_dilation: false,
    dilation_process: null,
    dilation_deadline: null
  },
  {
    id: '4',
    sei_number: '1630.01.0003000/2025-01',
    link: '#',
    ref_year: 2025,
    type: 'Apenso',
    description: 'Juntada de documentos ao processo principal de licitação.',
    tags: ['Licitação'],
    status: 'Finalizado com Desdobramentos',
    assigned_to: 'Maria Oliveira',
    initials: 'MO',
    notes: 'Apensado ao processo 1450/2025.',
    received_date: '2025-02-01',
    deadline: '2025-02-05',
    response_date: '2025-02-04',
    has_dilation: false,
    dilation_process: null,
    dilation_deadline: null
  },
  {
    id: '5',
    sei_number: '1630.01.0001880/2025-22',
    link: '#',
    ref_year: 2025,
    type: 'Denúncia',
    description: 'Averiguação de suposta irregularidade na compra de medicamentos.',
    tags: ['Jurídico', 'Sigiloso'],
    status: 'Acompanhamento especial',
    assigned_to: 'Jurídico Central',
    initials: 'JC',
    notes: 'Prioridade máxima solicitada pelo Gabinete.',
    received_date: '2025-01-28',
    deadline: '2025-02-10',
    response_date: null,
    has_dilation: false,
    dilation_process: null,
    dilation_deadline: null
  },
  {
    id: '6',
    sei_number: '1630.01.0004120/2025-66',
    link: '#',
    ref_year: 2025,
    type: 'Consulta',
    description: 'Consulta sobre viabilidade técnica de nova sede regional.',
    tags: ['Infraestrutura'],
    status: 'Aguarda resposta',
    assigned_to: 'Engenharia',
    initials: 'EG',
    notes: '',
    received_date: '2025-02-12',
    deadline: '2025-03-12',
    response_date: null,
    has_dilation: false,
    dilation_process: null,
    dilation_deadline: null
  },
  {
    id: '7',
    sei_number: '1630.01.0000999/2024-12',
    link: '#',
    ref_year: 2024,
    type: 'Prestação de Contas',
    description: 'Prestação de contas final do convênio XYZ.',
    tags: ['Convênio', 'Financeiro'],
    status: 'Finalizado e Concluído',
    assigned_to: 'Ana Silva',
    initials: 'AS',
    notes: 'Aprovado sem ressalvas.',
    received_date: '2024-12-01',
    deadline: '2024-12-31',
    response_date: '2024-12-28',
    has_dilation: false,
    dilation_process: null,
    dilation_deadline: null
  },
  {
    id: '8',
    sei_number: '1630.01.0005500/2025-01',
    link: '#',
    ref_year: 2025,
    type: 'Licitação',
    description: 'Processo de aquisição de equipamentos de TI.',
    tags: ['TI', 'Licitação'],
    status: 'Aguarda resposta',
    assigned_to: 'Setor de Compras',
    initials: 'SC',
    notes: 'Aguardando cotações.',
    received_date: '2025-03-01',
    deadline: '2025-03-20',
    response_date: null,
    has_dilation: false,
    dilation_process: null,
    dilation_deadline: null
  },
  {
    id: '9',
    sei_number: '1630.01.0006600/2025-02',
    link: '#',
    ref_year: 2025,
    type: 'Pessoal',
    description: 'Solicitação de férias e abono pecuniário.',
    tags: ['RH'],
    status: 'Finalizado e Concluído',
    assigned_to: 'Recursos Humanos',
    initials: 'RH',
    notes: 'Deferido.',
    received_date: '2025-03-05',
    deadline: '2025-03-10',
    response_date: '2025-03-08',
    has_dilation: false,
    dilation_process: null,
    dilation_deadline: null
  },
  {
    id: '10',
    sei_number: '1630.01.0007700/2025-03',
    link: '#',
    ref_year: 2025,
    type: 'Administrativo',
    description: 'Renovação do contrato de limpeza.',
    tags: ['Contratos'],
    status: 'Acompanhamento especial',
    assigned_to: 'Gestão de Contratos',
    initials: 'GC',
    notes: 'Verificar cláusulas de reajuste.',
    received_date: '2025-03-10',
    deadline: '2025-04-10',
    response_date: null,
    has_dilation: false,
    dilation_process: null,
    dilation_deadline: null
  },
  {
    id: '11',
    sei_number: '1630.01.0008800/2025-04',
    link: '#',
    ref_year: 2025,
    type: 'Financeiro',
    description: 'Pagamento de diárias para viagem técnica.',
    tags: ['Financeiro'],
    status: 'Aguarda resposta',
    assigned_to: 'Financeiro',
    initials: 'FN',
    notes: 'Aguardando comprovantes.',
    received_date: '2025-03-12',
    deadline: '2025-03-15',
    response_date: null,
    has_dilation: false,
    dilation_process: null,
    dilation_deadline: null
  },
  {
    id: '12',
    sei_number: '1630.01.0009900/2025-05',
    link: '#',
    ref_year: 2025,
    type: 'Jurídico',
    description: 'Parecer sobre nova legislação estadual.',
    tags: ['Jurídico', 'Normas'],
    status: 'Finalizado com Desdobramentos',
    assigned_to: 'Procuradoria',
    initials: 'PR',
    notes: 'Parecer favorável com ressalvas.',
    received_date: '2025-03-15',
    deadline: '2025-03-25',
    response_date: '2025-03-24',
    has_dilation: false,
    dilation_process: null,
    dilation_deadline: null
  },
  {
    id: '13',
    sei_number: '1630.01.0010000/2025-06',
    link: '#',
    ref_year: 2025,
    type: 'Comunicação',
    description: 'Aprovação de material gráfico para campanha.',
    tags: ['Marketing'],
    status: 'Aguarda resposta',
    assigned_to: 'Comunicação',
    initials: 'CM',
    notes: 'Aguardando aprovação final.',
    received_date: '2025-03-18',
    deadline: '2025-03-22',
    response_date: null,
    has_dilation: false,
    dilation_process: null,
    dilation_deadline: null
  },
  {
    id: '14',
    sei_number: '1630.01.0011100/2025-07',
    link: '#',
    ref_year: 2025,
    type: 'TI',
    description: 'Atualização do parque tecnológico.',
    tags: ['TI', 'Infraestrutura'],
    status: 'Acompanhamento especial',
    assigned_to: 'TI Suporte',
    initials: 'TS',
    notes: 'Projeto piloto em andamento.',
    received_date: '2025-03-20',
    deadline: '2025-04-20',
    response_date: null,
    has_dilation: false,
    dilation_process: null,
    dilation_deadline: null
  },
  {
    id: '15',
    sei_number: '1630.01.0012200/2025-08',
    link: '#',
    ref_year: 2025,
    type: 'Obras',
    description: 'Reforma do auditório principal.',
    tags: ['Obras', 'Infraestrutura'],
    status: 'Aguarda resposta',
    assigned_to: 'Engenharia',
    initials: 'EG',
    notes: 'Aguardando liberação orçamentária.',
    received_date: '2025-03-22',
    deadline: '2025-05-22',
    response_date: null,
    has_dilation: false,
    dilation_process: null,
    dilation_deadline: null
  },
  {
    id: '16',
    sei_number: '1630.01.0013300/2025-09',
    link: '#',
    ref_year: 2025,
    type: 'Transporte',
    description: 'Manutenção da frota de veículos.',
    tags: ['Logística'],
    status: 'Finalizado e Concluído',
    assigned_to: 'Logística',
    initials: 'LG',
    notes: 'Manutenção realizada.',
    received_date: '2025-03-25',
    deadline: '2025-03-30',
    response_date: '2025-03-29',
    has_dilation: false,
    dilation_process: null,
    dilation_deadline: null
  },
  {
    id: '17',
    sei_number: '1630.01.0014400/2025-10',
    link: '#',
    ref_year: 2025,
    type: 'Patrimônio',
    description: 'Inventário anual de bens móveis.',
    tags: ['Patrimônio'],
    status: 'Aguarda resposta',
    assigned_to: 'Patrimônio',
    initials: 'PT',
    notes: 'Contagem em andamento.',
    received_date: '2025-04-01',
    deadline: '2025-06-01',
    response_date: null,
    has_dilation: false,
    dilation_process: null,
    dilation_deadline: null
  },
  {
    id: '18',
    sei_number: '1630.01.0015500/2025-11',
    link: '#',
    ref_year: 2025,
    type: 'Treinamento',
    description: 'Curso de capacitação em gestão pública.',
    tags: ['RH', 'Capacitação'],
    status: 'Finalizado com Desdobramentos',
    assigned_to: 'RH Treinamento',
    initials: 'RT',
    notes: 'Certificados emitidos. Avaliação de impacto pendente.',
    received_date: '2025-04-05',
    deadline: '2025-04-10',
    response_date: '2025-04-09',
    has_dilation: false,
    dilation_process: null,
    dilation_deadline: null
  },
  {
    id: '19',
    sei_number: '1630.01.0016600/2025-12',
    link: '#',
    ref_year: 2025,
    type: 'Eventos',
    description: 'Organização do congresso anual.',
    tags: ['Eventos', 'Comunicação'],
    status: 'Acompanhamento especial',
    assigned_to: 'Comissão de Eventos',
    initials: 'CE',
    notes: 'Definir palestrantes.',
    received_date: '2025-04-10',
    deadline: '2025-08-10',
    response_date: null,
    has_dilation: false,
    dilation_process: null,
    dilation_deadline: null
  },
  {
    id: '20',
    sei_number: '1630.01.0017700/2025-13',
    link: '#',
    ref_year: 2025,
    type: 'Segurança',
    description: 'Instalação de câmeras de monitoramento.',
    tags: ['Segurança', 'Infraestrutura'],
    status: 'Aguarda resposta',
    assigned_to: 'Segurança Institucional',
    initials: 'SI',
    notes: 'Aguardando visita técnica.',
    received_date: '2025-04-15',
    deadline: '2025-05-15',
    response_date: null,
    has_dilation: false,
    dilation_process: null,
    dilation_deadline: null
  },
  {
    id: '21',
    sei_number: '1630.01.0018800/2025-14',
    link: '#',
    ref_year: 2025,
    type: 'Protocolo',
    description: 'Recebimento de correspondências oficiais.',
    tags: ['Administrativo'],
    status: 'Finalizado e Concluído',
    assigned_to: 'Protocolo',
    initials: 'PR',
    notes: 'Distribuído aos setores.',
    received_date: '2025-04-20',
    deadline: '2025-04-21',
    response_date: '2025-04-20',
    has_dilation: false,
    dilation_process: null,
    dilation_deadline: null
  },
  {
    id: '22',
    sei_number: '1630.01.0019900/2025-15',
    link: '#',
    ref_year: 2025,
    type: 'Arquivo',
    description: 'Digitalização do arquivo morto.',
    tags: ['Arquivo', 'TI'],
    status: 'Aguarda resposta',
    assigned_to: 'Gestão de Documentos',
    initials: 'GD',
    notes: 'Projeto em fase de planejamento.',
    received_date: '2025-05-01',
    deadline: '2025-12-31',
    response_date: null,
    has_dilation: false,
    dilation_process: null,
    dilation_deadline: null
  }
];

export const mockDocuments = [
  {
    id: 'doc-001',
    title: 'Documento Técnico - SOMA',
    type: 'PDF',
    size: '2.5 MB',
    createdAt: '2025-12-01T10:00:00Z',
  },
  {
    id: 'doc-002',
    title: 'Planilha de Custos - 2025',
    type: 'XLSX',
    size: '1.2 MB',
    createdAt: '2025-12-02T14:30:00Z',
  },
  {
    id: 'doc-003',
    title: 'Ata de Reunião - Diretoria',
    type: 'DOCX',
    size: '500 KB',
    createdAt: '2025-12-03T09:00:00Z',
  }
];

export const mockDashboardData = {
  totalProcesses: mockSeiProcesses.length,
  pendingDocuments: 5,
  completed: mockSeiProcesses.filter(p => p.status.includes('Finalizado')).length,
};

// Histórico inicial (seed) caso o usuário limpe tudo, ou apenas para referência
// Histórico inicial (seed)
export const mockInitialHistory = [
  {
    id: 'sei-1',
    process: '1630.01.0001450/2025-42',
    title: '1630.01.0001450/2025-42',
    path: '/sei/1',
    pinned: true,
    favorited: true,
    accessedAt: new Date(new Date().setHours(new Date().getHours() - 1)).toISOString(), // 1 hora atrás
  },
  {
    id: 'doc-001',
    process: 'Documento Técnico - SOMA',
    title: 'Documento Técnico - SOMA',
    path: '/documents/doc-001',
    pinned: true,
    favorited: false,
    accessedAt: new Date(new Date().setHours(new Date().getHours() - 2)).toISOString(), // 2 horas atrás
  },
  {
    id: 'sei-2',
    process: '1630.01.0002100/2025-11',
    title: '1630.01.0002100/2025-11',
    path: '/sei/2',
    pinned: false,
    favorited: false,
    accessedAt: new Date(new Date().setDate(new Date().getDate() - 1)).toISOString(), // Ontem
  },
  {
    id: 'doc-002',
    process: 'Planilha de Custos - 2025',
    title: 'Planilha de Custos - 2025',
    path: '/documents/doc-002',
    pinned: false,
    favorited: true,
    accessedAt: new Date(new Date().setDate(new Date().getDate() - 2)).toISOString(), // 2 dias atrás
  },
  {
    id: 'sei-5',
    process: '1630.01.0001880/2025-22',
    title: '1630.01.0001880/2025-22',
    path: '/sei/5',
    pinned: false,
    favorited: false,
    accessedAt: new Date(new Date().setDate(new Date().getDate() - 5)).toISOString(), // 5 dias atrás
  }
];

export const getSeiProcesses = async () => {
  // Simular delay de rede
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve(mockSeiProcesses);
    }, 800);
  });
};
