export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function MainLayout({ children }) {
  return (
    <div className="main-layout-wrapper">
      {children}
    </div>
  );
}